### ISSUE TITLE
[EPIC] Aquarius Scaling Issues

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/aquarius#323]
Near-term Tactics:
- [x] Stress tests - [Aqua-319](https://github.com/oceanprotocol/aquarius/issues/319) (Marian)
- [x] Multiple replicas of Aquarius [Aqua-325](https://github.com/oceanprotocol/aquarius/issues/325) (Marian)
- [x] Increase number of workers, use gevents for thread scheduling and use /dev/shm for gunicorn (#326) (Alex)
- [x] Hotfix tinkering taking away load stress from Aquarius [Market-254](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/254) ()
- [x] Tech spike: TheGraph for some uses [Aqua-324](https://github.com/oceanprotocol/multi-repo-issue/issues/41) (Ahmed)

Maybe (depends on tech spike above):
- [ ] TheGraph for some uses [Aqua-324](https://github.com/oceanprotocol/aquarius/issues/324) (Ahmed)

Only if needed:
- Replace flask/gunicorn with a more performant framework [Aqua-327](https://github.com/oceanprotocol/aquarius/issues/327)
- Python performance optimizations 
- Caching of responses. Why: many queries are very similar  (Team?)
