### ISSUE TITLE
Identify if Aquarius needs more REST API tests, and add as needed

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/aquarius#562]
**Motivation**

From PM team mtgs, a recurring discussion was: ask BE team to run Ocean Market FE locally to test BE changes. A constraint is that it requires base JS & node experience from BE. Then we realized there's a simpler way that doesn't have this constraint: simply make sure that there are really great tests for the Aqua endpoints that Ocean Market is hitting.

**TODOs for this issue**
- [ ] identify the Aqua endpoint(s) that Ocean Market is using
- [ ] brainstorm how to make these more robust. A starting point: have a few sample ElasticSearch queries. Even though it's a pass through, a few sample ones here can ensure that it truly works
- [ ] from previous step, choose which tests to write, and write them
 
Related issues:
- "Sorting by _score is not working" [aqua # 493](https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/aquarius/493)
- [aqua # 404](https://github.com/oceanprotocol/aquarius/issues/404)

**Comment by AnaLoznianu** [comment]
Linked issue: https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/aquarius/404

**Comment by calina-c** [comment]
@trentmc we have 96% coverage overall, and 100% over the API endpoints. The elasticsearch query endpoint has been improved to show any errors coming from Elasticsearch and show them to the user, helping with debugging their own queries, if the queries themselves are wrong.

In my opinion, it is overkill to create a sample ES and test each query. It would be a great deal of effort for only a marginal improvement. If any changes are made to the ES query endpoint, I think we can test them with a quick reindexing of mainnet. Do you think we can close this ticket?

**Comment by AnaLoznianu** [comment]
@trentmc, @alexcos20 Based on @calina-c's comment, do you still think is necessary to add more tests or we can close this ticket?

**Comment by trentmc** [comment]
>The elasticsearch query endpoint has been improved to show any errors coming from Elasticsearch and show them to the user, helping with debugging their own queries

Perfect to hear. This was the root of the complaints, from what I gather in the PM meetings. Given that we have this, and 95% coverage otherwise, we're good to go. Thanks for investigating.

Closing.
