### ISSUE TITLE
Aquarius README is cumbersome

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/aquarius#563]
**Motivation**

We want Aquarius to be easier to use. Its README is long and has a lot of important content. However it's not very approachable. 
- For example, there is no TOC. 
- And there are other points of friction for various users: (a) devs consuming its API, (b) devs wanting to develop further.
- For devs wanting to develop it further, the process to deploy a new Aquarius library is not really there

**TODOs**

- [x] Add a TOC. Inspired by ocean.py.  The TOC and related content should make it obvious for each type of user what to do
- [ ] Add a "developers flow" inspired by ocean.py. Eg a special subpage developers.md, linked from main page
- [ ] In the "developers flow" page, one of the later sections should have a clearly-defined release process. E.g. inspired by ocean.py, have a new page release-process.md, linked from developers.md
- [ ] Identify any other points of friction in the README, and try to remove them. When the "high bang for buck" stuff is done (you'll feel it), consider this ticket complete

**Comment by calina-c** [comment]
@trentmc I propose we close this ticket since we have the multi-repo one for discussion on how to update the READMEs with release processes. Otherwise, I think the other points pertaining to this ticket have been addressed.

**Comment by AnaLoznianu** [comment]
Linked aqua release process issue: https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/aquarius/568
